import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <aside className={"fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"}>
                <div className={"h-full px-3 py-4 overflow-y-auto bg-gray-50"}>
                    <ul className={"space-y-2 font-medium"}>
                        <li>
                            <Link href={"/"} className="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group">
                                <span className="ms-3 flex item-center justify-center gap-3"><i className="fi fi-rr-house-chimney"></i>Home</span>
                            </Link>
                            <Link href={"/routing"} className={"flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group"}>
                                <span className="ms-3 flex item-center justify-center gap-3"><i className="fi fi-rr-route"></i>Routing</span>
                            </Link>
                        </li>
                    </ul>
                </div>
            </aside>
            <div className={"p-4 sm:ml-64"}>
                <div className={"p-4 rounded-lg"}>
                    {children}
                </div>
            </div>
        </body>
        </html>
    );
}
